DROP TABLE IF EXISTS BITACORA_ACCESO_API;


CREATE TABLE BITACORA_ACCESO_API(
	ID_BITACORA_ACCESO_API long AUTO_INCREMENT PRIMARY KEY NOT NULL,
	CODIGO_API varchar(20) NOT NULL,
	FECHA_CONSULTA datetime NOT NULL
);